#include "hdf5_particle.h"
namespace mpm {
namespace hdf5::particle {
const size_t dst_offset[NFIELDS] = {
    HOFFSET(HDF5Particle, id),
    HOFFSET(HDF5Particle, cell_id),
    HOFFSET(HDF5Particle, material_id),
    HOFFSET(HDF5Particle, liquid_material_id),
    HOFFSET(HDF5Particle, current_time),   
    HOFFSET(HDF5Particle, mass),
    HOFFSET(HDF5Particle, liquid_mass),
    HOFFSET(HDF5Particle, ice_mass),
    HOFFSET(HDF5Particle, hydrate_mass),
    HOFFSET(HDF5Particle, gas_mass),                    
    HOFFSET(HDF5Particle, volume),
    HOFFSET(HDF5Particle, density),
    HOFFSET(HDF5Particle, liquid_density),
    HOFFSET(HDF5Particle, ice_density),
    HOFFSET(HDF5Particle, hydrate_density),
    HOFFSET(HDF5Particle, gas_density),                
    HOFFSET(HDF5Particle, porosity),
    HOFFSET(HDF5Particle, liquid_saturation),
    HOFFSET(HDF5Particle, ice_saturation),
    HOFFSET(HDF5Particle, hydrate_saturation),
    HOFFSET(HDF5Particle, gas_saturation),              
    HOFFSET(HDF5Particle, liquid_fraction),
    HOFFSET(HDF5Particle, ice_fraction),
    HOFFSET(HDF5Particle, hydrate_fraction),
    HOFFSET(HDF5Particle, gas_fraction),        
    HOFFSET(HDF5Particle, viscosity), 
    HOFFSET(HDF5Particle, permeability),
    HOFFSET(HDF5Particle, liquid_permeability),
    HOFFSET(HDF5Particle, gas_permeability),                               
    HOFFSET(HDF5Particle, pressure),
    HOFFSET(HDF5Particle, pore_pressure),
    HOFFSET(HDF5Particle, pore_liquid_pressure),
    HOFFSET(HDF5Particle, pore_ice_pressure),         
    HOFFSET(HDF5Particle, liquid_pressure),
    HOFFSET(HDF5Particle, gas_pressure),
    HOFFSET(HDF5Particle, temperature),
    HOFFSET(HDF5Particle, PIC_temperature),
    HOFFSET(HDF5Particle, coord_x),
    HOFFSET(HDF5Particle, coord_y),
    HOFFSET(HDF5Particle, coord_z),
    HOFFSET(HDF5Particle, displacement_x),
    HOFFSET(HDF5Particle, displacement_y),
    HOFFSET(HDF5Particle, displacement_z),
    HOFFSET(HDF5Particle, nsize_x),
    HOFFSET(HDF5Particle, nsize_y),
    HOFFSET(HDF5Particle, nsize_z),
    HOFFSET(HDF5Particle, velocity_x),
    HOFFSET(HDF5Particle, velocity_y),
    HOFFSET(HDF5Particle, velocity_z),
    HOFFSET(HDF5Particle, liquid_velocity_x),
    HOFFSET(HDF5Particle, liquid_velocity_y),
    HOFFSET(HDF5Particle, liquid_velocity_z),
    HOFFSET(HDF5Particle, gas_velocity_x),
    HOFFSET(HDF5Particle, gas_velocity_y),
    HOFFSET(HDF5Particle, gas_velocity_z),    
    HOFFSET(HDF5Particle, stress_xx),
    HOFFSET(HDF5Particle, stress_yy),
    HOFFSET(HDF5Particle, stress_zz),
    HOFFSET(HDF5Particle, tau_xy),
    HOFFSET(HDF5Particle, tau_yz),
    HOFFSET(HDF5Particle, tau_xz),
    HOFFSET(HDF5Particle, strain_xx),
    HOFFSET(HDF5Particle, strain_yy),
    HOFFSET(HDF5Particle, strain_zz),
    HOFFSET(HDF5Particle, gamma_xy),
    HOFFSET(HDF5Particle, gamma_yz),
    HOFFSET(HDF5Particle, gamma_xz),
    HOFFSET(HDF5Particle, thermal_strain_xx),
    HOFFSET(HDF5Particle, thermal_strain_yy),
    HOFFSET(HDF5Particle, thermal_strain_zz),
    HOFFSET(HDF5Particle, thermal_gamma_xy),
    HOFFSET(HDF5Particle, thermal_gamma_yz),
    HOFFSET(HDF5Particle, thermal_gamma_xz),
    HOFFSET(HDF5Particle, liquid_strain_xx),
    HOFFSET(HDF5Particle, liquid_strain_yy),
    HOFFSET(HDF5Particle, liquid_strain_zz),
    HOFFSET(HDF5Particle, liquid_gamma_xy),
    HOFFSET(HDF5Particle, liquid_gamma_yz),
    HOFFSET(HDF5Particle, liquid_gamma_xz),
    HOFFSET(HDF5Particle, epsilon_v),
    HOFFSET(HDF5Particle, thermal_epsilon_v),      
    HOFFSET(HDF5Particle, fxx),
    HOFFSET(HDF5Particle, fxy),
    HOFFSET(HDF5Particle, fxz),
    HOFFSET(HDF5Particle, fyx),
    HOFFSET(HDF5Particle, fyy),
    HOFFSET(HDF5Particle, fyz),
    HOFFSET(HDF5Particle, fzx),
    HOFFSET(HDF5Particle, fzy),
    HOFFSET(HDF5Particle, fzz),
    HOFFSET(HDF5Particle, fabric),
    HOFFSET(HDF5Particle, rotation_xy),
    HOFFSET(HDF5Particle, rotation_yz),
    HOFFSET(HDF5Particle, rotation_xz),
    HOFFSET(HDF5Particle, svars[0]),
    HOFFSET(HDF5Particle, svars[1]),
    HOFFSET(HDF5Particle, svars[2]),
    HOFFSET(HDF5Particle, svars[3]),
    HOFFSET(HDF5Particle, svars[4]),
    HOFFSET(HDF5Particle, svars[5]),
    HOFFSET(HDF5Particle, status),
    HOFFSET(HDF5Particle, nstate_vars)  
};

// Get size of particle
HDF5Particle particle;
const size_t dst_sizes[NFIELDS] = {
    sizeof(particle.id),
    sizeof(particle.cell_id),
    sizeof(particle.material_id),
    sizeof(particle.liquid_material_id),    
    sizeof(particle.current_time),    
    sizeof(particle.mass),
    sizeof(particle.liquid_mass),  
    sizeof(particle.ice_mass),
    sizeof(particle.hydrate_mass),  
    sizeof(particle.gas_mass),          
    sizeof(particle.volume),
    sizeof(particle.density),  
    sizeof(particle.liquid_density),  
    sizeof(particle.ice_density),
    sizeof(particle.hydrate_density),  
    sizeof(particle.gas_density),              
    sizeof(particle.porosity),  
    sizeof(particle.liquid_saturation),
    sizeof(particle.ice_saturation),
    sizeof(particle.hydrate_saturation),
    sizeof(particle.gas_saturation),   
    sizeof(particle.liquid_fraction),    
    sizeof(particle.ice_fraction),
    sizeof(particle.hydrate_fraction),
    sizeof(particle.gas_fraction),    
    sizeof(particle.viscosity), 
    sizeof(particle.permeability),
    sizeof(particle.liquid_permeability),
    sizeof(particle.gas_permeability),               
    sizeof(particle.pressure),
    sizeof(particle.pore_pressure),
    sizeof(particle.pore_liquid_pressure),
    sizeof(particle.pore_ice_pressure),
    sizeof(particle.liquid_pressure),
    sizeof(particle.gas_pressure),            
    sizeof(particle.temperature),
    sizeof(particle.PIC_temperature),      
    sizeof(particle.coord_x),
    sizeof(particle.coord_y),
    sizeof(particle.coord_z),
    sizeof(particle.displacement_x),
    sizeof(particle.displacement_y),
    sizeof(particle.displacement_z),
    sizeof(particle.nsize_x),
    sizeof(particle.nsize_y),
    sizeof(particle.nsize_z),
    sizeof(particle.velocity_x),
    sizeof(particle.velocity_y),
    sizeof(particle.velocity_z),
    sizeof(particle.liquid_velocity_x),
    sizeof(particle.liquid_velocity_y),
    sizeof(particle.liquid_velocity_z),
    sizeof(particle.gas_velocity_x),
    sizeof(particle.gas_velocity_y),
    sizeof(particle.gas_velocity_z),    
    sizeof(particle.stress_xx),
    sizeof(particle.stress_yy),
    sizeof(particle.stress_zz),
    sizeof(particle.tau_xy),
    sizeof(particle.tau_yz),
    sizeof(particle.tau_xz),
    sizeof(particle.strain_xx),
    sizeof(particle.strain_yy),
    sizeof(particle.strain_zz),
    sizeof(particle.gamma_xy),
    sizeof(particle.gamma_yz),
    sizeof(particle.gamma_xz),
    sizeof(particle.thermal_strain_xx),
    sizeof(particle.thermal_strain_yy),
    sizeof(particle.thermal_strain_zz),
    sizeof(particle.thermal_gamma_xy),
    sizeof(particle.thermal_gamma_yz),
    sizeof(particle.thermal_gamma_xz),
    sizeof(particle.liquid_strain_xx),
    sizeof(particle.liquid_strain_yy),
    sizeof(particle.liquid_strain_zz),
    sizeof(particle.liquid_gamma_xy),
    sizeof(particle.liquid_gamma_yz),
    sizeof(particle.liquid_gamma_xz),
    sizeof(particle.epsilon_v),
    sizeof(particle.thermal_epsilon_v),
    sizeof(particle.fxx),
    sizeof(particle.fxy),
    sizeof(particle.fxz),
    sizeof(particle.fyx),
    sizeof(particle.fyy),
    sizeof(particle.fyz),
    sizeof(particle.fzx),
    sizeof(particle.fzy),
    sizeof(particle.fzz),
    sizeof(particle.fabric),  
    sizeof(particle.rotation_xy),
    sizeof(particle.rotation_yz),
    sizeof(particle.rotation_xz),
    sizeof(particle.svars[0]),
    sizeof(particle.svars[1]),
    sizeof(particle.svars[2]),
    sizeof(particle.svars[3]),
    sizeof(particle.svars[4]),
    sizeof(particle.svars[5]),
    sizeof(particle.status),
    sizeof(particle.nstate_vars)    
};

// Define particle field information
const char* field_names[NFIELDS] = {
    "id",
    "cell_id",
    "material_id",
    "liquid_material_id",    
    "current_time",
    "mass",
    "liquid_mass",
    "ice_mass",
    "hydrate_mass",
    "gas_mass",        
    "volume",
    "density",
    "liquid_density",
    "ice_density",
    "hydrate_density",
    "gas_density",    
    "porosity",
    "liquid_saturation",
    "ice_saturation",
    "hydrate_saturation",
    "gas_saturation",            
    "liquid_fraction",   
    "ice_fraction",
    "hydrate_fraction",   
    "gas_fraction",     
    "viscosity",   
    "permeability",
    "liquid_permeability",
    "gas_permeability",                       
    "pressure",
    "pore_pressure",
    "pore_liquid_pressure",   
    "pore_ice_pressure",
    "liquid_pressure",
    "gas_pressure",                          
    "temperature",
    "PIC_temperature",    
    "coord_x",
    "coord_y",
    "coord_z",
    "displacement_x",
    "displacement_y",
    "displacement_z",
    "nsize_x",
    "nsize_y",
    "nsize_z",
    "velocity_x",
    "velocity_y",
    "velocity_z",
    "liquid_velocity_x",
    "liquid_velocity_y",
    "liquid_velocity_z",
    "gas_velocity_x",
    "gas_velocity_y",
    "gas_velocity_z",    
    "stress_xx",
    "stress_yy",
    "stress_zz",
    "tau_xy",
    "tau_yz",
    "tau_xz",
    "strain_xx",
    "strain_yy",
    "strain_zz",
    "gamma_xy",
    "gamma_yz",
    "gamma_xz",
    "thermal_strain_xx",
    "thermal_strain_yy",
    "thermal_strain_zz",
    "thermal_gamma_xy",
    "thermal_gamma_yz",
    "thermal_gamma_xz",
    "liquid_strain_xx",
    "liquid_strain_yy",
    "liquid_strain_zz",
    "liquid_gamma_xy",
    "liquid_gamma_yz",
    "liquid_gamma_xz",
    "epsilon_v",
    "thermal_epsilon_v",
    "fxx",
    "fxy",
    "fxz",
    "fyx",
    "fyy",
    "fyz",
    "fzx",
    "fzy",
    "fzz",
    "fabric",    
    "rotation_xy",
    "rotation_yz",
    "rotation_xz",
    "svars_0",
    "svars_1",
    "svars_2",
    "svars_3",
    "svars_4",
    "svars_5",
    "status",
    "nstate_vars"
    };

// Initialise field types
const hid_t field_type[NFIELDS] = {
    H5T_NATIVE_LLONG, 
    H5T_NATIVE_LLONG,           
    H5T_NATIVE_UINT,            
    H5T_NATIVE_UINT,     
    H5T_NATIVE_DOUBLE,              
    H5T_NATIVE_DOUBLE, 
    H5T_NATIVE_DOUBLE,             
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,              
    H5T_NATIVE_DOUBLE, 
    H5T_NATIVE_DOUBLE,             
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,    
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,                     
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,         
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE, 
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,          
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE,         
    H5T_NATIVE_DOUBLE,     
    H5T_NATIVE_HBOOL,                      
    H5T_NATIVE_UINT    
    };         
}  // namespace hdf5::particle
}  // namespace mpm





  
